[2022-09-14T13:11:32.228+0300] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: First-Dag.RandomNumberGeneratorA manual__2022-09-14T10:11:30.152193+00:00 [queued]>
[2022-09-14T13:11:32.241+0300] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: First-Dag.RandomNumberGeneratorA manual__2022-09-14T10:11:30.152193+00:00 [queued]>
[2022-09-14T13:11:32.242+0300] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-14T13:11:32.242+0300] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-09-14T13:11:32.242+0300] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-14T13:11:32.260+0300] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): RandomNumberGeneratorA> on 2022-09-14 10:11:30.152193+00:00
[2022-09-14T13:11:32.262+0300] {standard_task_runner.py:52} INFO - Started process 11746 to run task
[2022-09-14T13:11:32.265+0300] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'First-Dag', 'RandomNumberGeneratorA', 'manual__2022-09-14T10:11:30.152193+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/First_Dag.py', '--cfg-path', '/tmp/tmp4fb8l9rf', '--error-file', '/tmp/tmpazxo8c8_']
[2022-09-14T13:11:32.266+0300] {standard_task_runner.py:80} INFO - Job 70: Subtask RandomNumberGeneratorA
[2022-09-14T13:11:32.324+0300] {task_command.py:371} INFO - Running <TaskInstance: First-Dag.RandomNumberGeneratorA manual__2022-09-14T10:11:30.152193+00:00 [running]> on host DESKTOP-6F0IB4Q.localdomain
[2022-09-14T13:11:32.387+0300] {taskinstance.py:1581} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=First-Dag
AIRFLOW_CTX_TASK_ID=RandomNumberGeneratorA
AIRFLOW_CTX_EXECUTION_DATE=2022-09-14T10:11:30.152193+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-14T10:11:30.152193+00:00
[2022-09-14T13:11:32.388+0300] {python.py:173} INFO - Done. Returned value was: 8
[2022-09-14T13:11:32.406+0300] {taskinstance.py:1407} INFO - Marking task as SUCCESS. dag_id=First-Dag, task_id=RandomNumberGeneratorA, execution_date=20220914T101130, start_date=20220914T101132, end_date=20220914T101132
[2022-09-14T13:11:32.437+0300] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-14T13:11:32.455+0300] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
